# Create & Save ML Model
This notebook mirrors `create_model.py` — generating synthetic data, training a `RandomForestRegressor`, and saving it to `model.joblib`.

## 1. Install Dependencies

In [1]:
!pip install scikit-learn numpy joblib

## 2. Imports

In [2]:
import joblib
import numpy as np
from sklearn.ensemble import RandomForestRegressor

## 3. Generate Synthetic Training Data
`RandomState(42)` seeds the RNG for reproducibility — running this notebook multiple times will always produce the same data.

In [3]:
# X: 100 samples × 4 features (values in range 0–1)
X = np.random.RandomState(42).rand(100, 4)

# y: 100 continuous target values (range 0–1)
y = np.random.RandomState(42).rand(100)

print(f'X shape : {X.shape}  (samples × features)')
print(f'y shape : {y.shape}  (target values)')
print(f'\nFirst 5 rows of X:\n{X[:5]}')
print(f'\nFirst 5 values of y:\n{y[:5]}')

X shape : (100, 4)  (samples × features)
y shape : (100,)  (target values)

First 5 rows of X:
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]

First 5 values of y:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


## 4. Train the Random Forest Regressor
Builds `n_estimators` decision trees and averages their predictions. `random_state=42` makes the model reproducible.

In [4]:
model = RandomForestRegressor(n_estimators=10, random_state=42)
model.fit(X, y)

print(f'Training complete.')
print(f'  n_estimators    : {model.n_estimators}')
print(f'  n_features_in_  : {model.n_features_in_}')
print(f'  Training score  : {model.score(X, y):.4f}')

Training complete.
  n_estimators    : 10
  n_features_in_  : 4
  Training score  : 0.7723


## 5. Inspect Feature Importances

In [5]:
for i, importance in enumerate(model.feature_importances_):
    print(f'  Feature {i}: {importance:.4f}')

  Feature 0: 0.2052
  Feature 1: 0.2573
  Feature 2: 0.2810
  Feature 3: 0.2565


## 6. Save the Model to Disk

In [6]:
joblib.dump(model, 'model.joblib')
print(f'✓ Model saved to model.joblib  |  n_features_in_: {model.n_features_in_}')

✓ Model saved to model.joblib  |  n_features_in_: 4


## 7. Verify — Reload & Run a Sample Prediction

In [7]:
loaded_model = joblib.load('model.joblib')

sample = np.array([[0.5, 0.3, 0.8, 0.1]])
prediction = loaded_model.predict(sample)[0]

print(f'Sample input  : {sample[0].tolist()}')
print(f'Prediction    : {prediction:.4f}')
print(f'Model reloaded successfully ✓')

Sample input  : [0.5, 0.3, 0.8, 0.1]
Prediction    : 0.3864
Model reloaded successfully ✓
